version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: my-portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume/data:/data
    